In [56]:
from pyspark.mllib.clustering import KMeans
from numpy import array
from pyspark import SparkContext
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option("max_columns", None)

In [57]:
uberfile = "/tmp/uber-raw-data-apr14.csv"
uberfile = "/tmp/uber-raw-data-noheader.csv"
uberrdd = sc.textFile(uberfile)
def project(rec):
    fields = rec.split(',')
    return fields
    
projection = uberrdd.map(lambda rec: project(rec))
n = projection.count()
trans = projection.map(lambda l: [ l[2], l[1]])

clusters = KMeans.train(trans, k=8, maxIterations=20, runs=20, initializationMode="random")

clusters.centers

[array([-74.20165533,  40.70056661]),
 array([-73.96472197,  40.68794231]),
 array([-73.98135645,  40.75580054]),
 array([-73.95892692,  40.78203687]),
 array([-73.87024718,  40.78137236]),
 array([-73.77949983,  40.65584848]),
 array([-74.00035393,  40.72766088]),
 array([-73.61633838,  40.97222233])]

In [55]:
import mplleaflet
def plotcenter(c):
    for cn in c:
        plt.scatter(cn[0] ,cn[1],color="r")      

plotcenter(clusters.centers)

mplleaflet.display()